import { Address } from "./Address"

export interface LineItem{
    prodID: number,
    prodQuantity: number
}

export interface Order{
    /**
    During creation, orderID is not known and generated by DB. When reading orders from DB,
    orderID is used as key in mapping
     */
    orderID?: string,
    userID: string,
    total: number,
    lineItems: LineItem[],
    paymentMode: string,
    shippingAddress: Address,
    shippingDate: Date,
    orderStatus: string,
    responseMessage: string
}
