export interface LineItem{
    prodID: number,
    prodQuantity: number
}
export interface Address{
    name: string,
    house: string,
    street: string,
    city: string,
    zip: string
}

export interface Order{
    /**
    During creation, orderID is not known and generated by DB. When reading orders from DB,
    orderID is used as key in mapping
     */
    orderID?: string,
    userID: string,
    total: number,
    lineItems: LineItem[],
    paymentMode: string,
    shippingAddress: Address,
    shippingDate: Date,
    orderStatus: string,
    responseMessage: string
}
