import { Address } from "./Address";

export interface Shipment{
    /**
    During creation, shipmentID is not known and generated by DB. When reading orders from DB,
    shipmentID is used as key in mapping
     */
    shipmentID?: string,
    shippingDate: Date,
    address: Address,
}
